// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntsoctffiqvrbgyeurjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50c29jdGZmaXF2cmJneWV1cmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzIzNzYsImV4cCI6MjA1NzgwODM3Nn0.9RA2K8b-Em80GyxW3ECnyoKQQPYoNEw2lLd72ZGxP_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);